[typescript]
extensions = ["ts", "tsx"]
keywords = ["break", "as", "any", "case", "implements", "boolean",
            "catch", "interface", "constructor", "class", "let",
            "declare", "const", "package", "get", "continue", "private",
            "module", "debugger", "protected", "require", "default",
            "public", "number", "delete", "static", "set", "do", "yield",
            "string", "else", "symbol", "enum", "type", "export", "from",
            "extends", "of", "false"]

[javascript]
extensions = ["js", "jsx"]
keywords = ["break", "as", "any", "case", "implements", "boolean",
            "catch", "interface", "constructor", "class", "let",
            "declare", "const", "package", "get", "continue", "private",
            "module", "debugger", "protected", "require", "default",
            "public", "number", "delete", "static", "set", "do", "yield",
            "string", "else", "symbol", "enum", "type", "export", "from",
            "extends", "of", "false"]

[rust]
extensions = ["rs"]
keywords = ["as", "async", "use", "await", "break", "const",
            "continue", "crate", "dyn", "else", "if", "let", 
            "enum", "extern", "false", "fn", "for", "match",
            "impl", "in", "loop", "mod", "move", "mut", "pub",
            "ref", "return", "Self", "self", "static", "struct",
            "super", "trait", "true", "type", "union", "unsafe",
            "use", "where", "while"]

[go]
extensions = ["go"]
keywords = ["go", "func", "type", "struct", "interface", "default", 
            "select", "case", "defer", "map", "chan", "else", "goto", 
            "package", "switch", "const", "fallthrough", "if", "range", 
            "continue", "for", "import", "return", "var"]

[ruby]
extensions = ["rb"]
keywords = ["BEGIN", "END", "alias", "and", "begin", "break", "case",
            "class", "def", "module", "next", "nil", "not", "or", "redo",
            "rescue", "retry", "return", "elsif", "and", "false", "ensure",
            "for", "if", "true", "undef", "unless", "do", "else", "super",
            "then", "until", "when", "while", "defined?", "self", "yield"]

[ocaml]
extensions = ["ml"]
keywords = []

[python]
extensions = ["py"]
keywords = []

[cpp]
extensions = ["cpp"]
keywords = []

[java]
extensions = ["java"]
keywords = []

[csharp]
extensions = ["cs"]
keywords = []

[swift]
extensions = ["swift"]
keywords = []

[scala]
extensions = ["scala", "sc"]
keywords = []

[kotlin]
extensions = ["kt"]
keywords = [""]

[elixir]
extensions = ["ex"]
keywords = []

[dart]
extensions = ["dart"]
keywords = []

[graphql]
extensions = ["graphql"]
keywords = []

[php]
extensions = ["php"]
keywords = []